const data = {
    cardData: [
        {
            "id": "AFG",
            "code": "Afghani",
            "name": "Afghanistan",
            "phone": "93",
            "capital": "Kabul",
            "languages": "Dani Persion, Pashto",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/color/48/null/flag-of-afghanistan.png",
        },
        {
            "id": "ALB",
            "code": "Lek",
            "name": "Albania",
            "phone": "355",
            "capital": "Tirane",
            "languages": "Albanian",
            "continent": "Europa",
            "emoji": "https://img.icons8.com/emoji/48/null/albania-emoji.png",
        },
        {
            "id": "DZA",
            "code": "Algerian Dinar",
            "name": "Algeria",
            "phone": "213",
            "capital": "Algiers",
            "languages": "Arabic; Tamazight; French",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/algeria-emoji.png",
        },
        {
            "id": "AND",
            "code": "Euro",
            "name": "Andorra",
            "phone": "376",
            "capital": "Andorra la Vella",
            "languages": "Catalan",
            "continent": "Europa",
            "emoji": "https://img.icons8.com/emoji/48/null/andorra-emoji.png",
        },
        {
            "id": "AGO",
            "code": "Kwanza",
            "name": "Angola",
            "phone": "355",
            "capital": "Luanda",
            "languages": "Portuguese",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/angola-emoji.png",
        },
        {
            "id": "ATG",
            "code": "East Caribbean Dollar",
            "name": "Antigua and Barbuda",
            "phone": "1 268",
            "capital": "Saint John's",
            "languages": "English",
            "continent": "North America",
            "emoji": "https://img.icons8.com/emoji/48/null/antigua--barbuda-emoji.png",
        },
        {
            "id": "ARG",
            "code": "Argentine Peso",
            "name": "Argetina",
            "phone": "54",
            "capital": "Buenos Aires",
            "languages": "Spanish",
            "continent": "South America",
            "emoji": "https://img.icons8.com/emoji/48/null/argentina-emoji.png",
        },
        {
            "id": "ARM",
            "code": "Dram",
            "name": "Armenia",
            "phone": "374",
            "capital": "Yerevan",
            "languages": "Armenian",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/armenia-emoji.png",
        },
        {
            "id": "AUS",
            "code": "Australian Dollar",
            "name": "Australia",
            "phone": "61",
            "capital": "Canberra",
            "languages": "English",
            "continent": "Oceania",
            "emoji": "https://img.icons8.com/emoji/48/null/australia-emoji.png",
        },
        {
            "id": "AUT",
            "code": "Euro",
            "name": "Austria",
            "phone": "43",
            "capital": "Vienna",
            "languages": "German",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/austria-emoji.png",
        },
        {
            "id": "AZE",
            "code": "Manat",
            "name": "Azerbaijan",
            "phone": "994",
            "capital": "Baku",
            "languages": "Azerbaijani",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/azerbaijan-emoji.png",
        },
        {
            "id": "BHS",
            "code": "Bahamian Dollar",
            "name": "The Bahamas",
            "phone": "1 242",
            "capital": "Nassau",
            "languages": "English",
            "continent": "North America",
            "emoji": "https://img.icons8.com/emoji/48/null/bahamas-emoji.png",
        },
        {
            "id": "BHR",
            "code": "Bahraini Dinar",
            "name": "Bahrain",
            "phone": "973",
            "capital": "Manama",
            "languages": "Arabic",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/bahrain-emoji.png",
        },
        {
            "id": "BGD",
            "code": "Taka",
            "name": "Bangladesh",
            "phone": "880",
            "capital": "Dhaka",
            "languages": "Bangla",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/bangladesh-emoji.png",
        },
        {
            "id": "BRB",
            "code": "Barbadian Dollar",
            "name": "Barbados",
            "phone": "1 246",
            "capital": "Bridgetown",
            "languages": "English",
            "continent": "North America",
            "emoji": "https://img.icons8.com/emoji/48/null/barbados-emoji.png",
        },
        {
            "id": "BLR",
            "code": "Belarusian Ruble",
            "name": "Belarus",
            "phone": "375",
            "capital": "Minsk",
            "languages": "Belarusian; Russian",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/belarus-emoji.png",
        },
        {
            "id": "BEL",
            "code": "Euro",
            "name": "Belgium",
            "phone": "32",
            "capital": "Brussels",
            "languages": "Dutch; French; German",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/belgium-emoji.png",
        },
        {
            "id": "BLZ",
            "code": "Belize Dollar",
            "name": "Belize",
            "phone": "501",
            "capital": "Belmopan",
            "languages": "English",
            "continent": "North America",
            "emoji": "https://img.icons8.com/emoji/48/null/belize-emoji.png",
        },
        {
            "id": "BEN",
            "code": "West African CFA Franc",
            "name": "Benin",
            "phone": "229",
            "capital": "Porto-Novo",
            "languages": "French",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/benin-emoji.png",
        },
        {
            "id": "BTN",
            "code": "Boliviano",
            "name": "Bhutan",
            "phone": "975",
            "capital": "Thimphu",
            "languages": "Spanish; Quechua; Aymara",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/bhutan-emoji.png",
        },
        {
            "id": "BOL",
            "code": "Boliviano",
            "name": "Bolivia",
            "phone": "591",
            "capital": "Sucre",
            "languages": "Spanish; Quechua; Aymara",
            "continent": "South America",
            "emoji": "https://img.icons8.com/emoji/48/null/bolivia-emoji.png",
        },
        {
            "id": "BIH",
            "code": "Convertible Mark",
            "name": "Bosnia and Herzegovina",
            "phone": "387",
            "capital": "Sarajevo",
            "languages": "Bosnian; Croatian; Serbian",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/bosnia--herzegovina-emoji.png",
        },
        {
            "id": "BWA",
            "code": "Pula",
            "name": "Botswana",
            "phone": "267",
            "capital": "Gaborone",
            "languages": "English; Tswana",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/botswana-emoji.png",
        },
        {
            "id": "BRA",
            "code": "Real",
            "name": "Brazil",
            "phone": "55",
            "capital": "Brasília",
            "languages": "Portuguese",
            "continent": "South America",
            "emoji": "https://img.icons8.com/emoji/48/null/brazil-emoji.png",
        },
        {
            "id": "BRN",
            "code": "Brunei Dollar",
            "name": "Brunei",
            "phone": "673",
            "capital": "Bandar Seri Begawan",
            "languages": "Malay",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/brunei-emoji.png",
        },
        {
            "id": "BGR",
            "code": "Lev",
            "name": "Bulgaria",
            "phone": "359",
            "capital": "Sofia",
            "languages": "Bulgarian",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/bulgaria-emoji.png",
        },
        {
            "id": "BFA",
            "code": "West African CFA Franc",
            "name": "Burkina Faso",
            "phone": "226",
            "capital": "Ouagadougou",
            "languages": "French",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/burkina-faso-emoji.png",
        },
        {
            "id": "BDI",
            "code": "Burundi Franc",
            "name": "Burundi",
            "phone": "257",
            "capital": "Bujumbura",
            "languages": "Kirundi; French",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/burundi-emoji.png",
        },
        {
            "id": "KHM",
            "code": "Riel",
            "name": "Cambodia",
            "phone": "855",
            "capital": "Phnom Penh",
            "languages": "Khmer",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/cambodia-emoji.png",
        },
        {
            "id": "CMR",
            "code": "Central African CFA Franc",
            "name": "Cameroon",
            "phone": "237",
            "capital": "Yaoundé",
            "languages": "French; English",
            "continent":"Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/cameroon-emoji.png",
        },
        {
            "id": "CAN",
            "code": "Canadian Dollar",
            "name": "Canada",
            "phone": "1",
            "capital": "Ottawa",
            "languages": "English; French",
            "continent": "North America",
            "emoji": "https://img.icons8.com/emoji/48/null/canada-emoji.png",
        },
        {
            "id": "CPV",
            "code": "Cape Verdean Escudo",
            "name": "Cape Verde",
            "phone": "238",
            "capital": "Praia",
            "languages": "Portuguese",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/cape-verde-emoji.png",
        },
        {
            "id": "CAF",
            "code": "Central African CFA Franc",
            "name": "Central African Republic",
            "phone": "236",
            "capital": "Bangui",
            "languages": "Sango; French",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/central-african-republic-emoji.png",
        },
        {
            "id": "TCD",
            "code": "Central African CFA Franc",
            "name": "Chad",
            "phone": "235",
            "capital": "N'Djamena",
            "languages": "French; Arabic",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/chad-emoji.png",
        },
        {
            "id": "CHN",
            "code": "Chinese Yuan",
            "name": "China",
            "phone": "86",
            "capital": "Beijing",
            "languages": "Mandarin",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/china-emoji.png",
        },
        {
            "id": "COL",
            "code": "Colombian Peso",
            "name": "Colombia",
            "phone": "57",
            "capital": "Bogotá",
            "languages": "Spanish",
            "continent": "South America",
            "emoji": "https://img.icons8.com/emoji/48/null/colombia-emoji.png",
        },
        {
            "id": "COM",
            "code": "Comorian Franc",
            "name": "Comoros",
            "phone": "269",
            "capital": "Moroni",
            "languages": "Comorian; Arabic; French",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/comoros-emoji.png",
        },
        {
            "id": "COD",
            "code": "AFG",
            "name": "Democratic Republic Of the Congo",
            "phone": "242",
            "capital": "Kinshasa",
            "languages": "French",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/color/48/null/democratic-republic-congo.png",
        },
        {
            "id": "COG",
            "code": "AFG",
            "name": "Republic of the Congo",
            "phone": "242",
            "capital": "Brazzavillea",
            "languages": "French",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/color/48/null/congo.png",
        },
        {
            "id": "CRC",
            "code": "Colon",
            "name": "Costa Rica",
            "phone": "506",
            "capital": "San José",
            "languages": "Spanish",
            "continent": "North America",
            "emoji": "https://img.icons8.com/emoji/48/null/costa-rica-emoji.png",
        },
        {
            "id": "CI",
            "code": "West African CFA Franc",
            "name": "Cote d'Ivoire (Ivory Coast)",
            "phone": "225",
            "capital": "Yamoussoukro; Abidjan",
            "languages": "French",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/cote-divoire-emoji.png",
        },
        {
            "id": "HRV",
            "code": "Croatian",
            "name": "Croatia",
            "phone": "385",
            "capital": "Zagreb",
            "languages": "Kuna",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/croatia-emoji.png",
        },
        {
            "id": "CUB",
            "code": "Cuban Peso",
            "name": "Cuba",
            "phone": "53",
            "capital": "Havana",
            "languages": "Spanish",
            "continent": "North America",
            "emoji": "https://img.icons8.com/emoji/48/null/cuba-emoji.png",
        },
        {
            "id": "CYP",
            "code": "Euro",
            "name": "Cyprus",
            "phone": "357",
            "capital": "Nicosia",
            "languages": "Greek; Turkish",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/cyprus-emoji.png",
        },
        {
            "id": "CZE",
            "code": "Czech Koruna",
            "name": "Czech Republic",
            "phone": "420",
            "capital": "Prague",
            "languages": "Czech; Slovak",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/czechia-emoji.png",
        },
        {
            "id": "DNK",
            "code": "Danish Krone",
            "name": "Denmark",
            "phone": "45",
            "capital": "Copenhagen",
            "languages": "Danish",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/denmark-emoji.png",
        },
        {
            "id": "DJI",
            "code": "Djiboutian Franc",
            "name": "Djibouti",
            "phone": "253",
            "capital": "Djibouti-city",
            "languages": "Arabic; French",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/djibouti-emoji.png",
        },
        {
            "id": "DMA",
            "code": "East Caribbean Dollar",
            "name": "Dominica",
            "phone": "1 767",
            "capital": "Roseau",
            "languages": "English; French; Antillean Creole",
            "continent": "North America",
            "emoji": "https://img.icons8.com/emoji/48/null/dominica-emoji.png",
        },
        {
            "id": "DOM",
            "code": "Dominican Peso",
            "name": "Dominican Republic",
            "phone": "1 809; 1 829; 1 849",
            "capital": "Santo Domingo",
            "languages": "Spanish",
            "continent": "North America",
            "emoji": "https://img.icons8.com/emoji/48/null/dominican-republic-emoji.png",
        },
        {
            "id": "TLS",
            "code": "United States Dollar",
            "name": "East Timor (Timor-Leste)",
            "phone": "670",
            "capital": "Dili",
            "languages": "Tetum; Portuguese; Iindonesian",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/color/48/null/timor-leste.png",
        },
        {
            "id": "ECU",
            "code": "United States Dollar",
            "name": "Ecuador",
            "phone": "593",
            "capital": "Quito",
            "languages": "Spanish",
            "continent": "South America",
            "emoji": "https://img.icons8.com/emoji/48/null/ecuador-emoji.png",
        },
        {
            "id": "EGY",
            "code": "Egyptian Pound",
            "name": "Egypt",
            "phone": "20",
            "capital": "Cairo",
            "languages": "Arabic",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/egypt-emoji.png",
        },
        {
            "id": "SLV",
            "code": "United States Dollar",
            "name": "El Salvador",
            "phone": "503",
            "capital": "San Salvador",
            "languages": "Spanish",
            "continent": "North America",
            "emoji": "https://img.icons8.com/emoji/48/null/el-salvador-emoji.png",
        },
        {
            "id": "GNQ",
            "code": "Central African CFA Franc",
            "name": "Equitorial Guinea",
            "phone": "240",
            "capital": "Malabo",
            "languages": "Spanish; French; Portuguese",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/equatorial-guinea-emoji.png",
        },
        {
            "id": "ERI",
            "code": "Nakfa",
            "name": "Eritrea",
            "phone": "291",
            "capital": "Asmara",
            "languages": "Arabic; Tigrinya; English",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/eritrea-emoji.png",
        },
        {
            "id": "EST",
            "code": "Estonian Kroon; Euro",
            "name": "Estonia",
            "phone": "372",
            "capital": "Tallinn",
            "languages": "Estonian",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/estonia-emoji.png",
        },
        {
            "id": "ETH",
            "code": "Birr",
            "name": "Ethiopia",
            "phone": "251",
            "capital": "Addis Ababa",
            "languages": "Amharic",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/ethiopia-emoji.png",
        },
        {
            "id": "FIN",
            "code": "Euro",
            "name": "Finland",
            "phone": "358",
            "capital": "Helsinki",
            "languages": "Finnish; Swedish",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/finland-emoji.png",
        },
        {
            "id": "FRA",
            "code": "Euro; CFP Franc",
            "name": "France",
            "phone": "33",
            "capital": "Paris",
            "languages": "French",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/france-emoji.png",
        },
        {
            "id": "GAB",
            "code": "Central African CFA Franc",
            "name": "Gabon",
            "phone": "241",
            "capital": "Libreville",
            "languages": "French",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/gabon-emoji.png",
        },
        {
            "id": "GMB",
            "code": "Dalasi",
            "name": "The Gambia",
            "phone": "220",
            "capital": "Banjul",
            "languages": "English",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/gambia-emoji.png",
        },
        {
            "id": "GEO",
            "code": "Lari",
            "name": "Georgia",
            "phone": "995",
            "capital": "Tbilisi",
            "languages": "Georgian",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/georgia-emoji.png",
        },
        {
            "id": "DEU",
            "code": "Euro",
            "name": "Germany",
            "phone": "49",
            "capital": "Berlin",
            "languages": "German",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/germany-emoji.png",
        },
        {
            "id": "GHA",
            "code": "Ghanaian Cedi",
            "name": "Ghana",
            "phone": "233",
            "capital": "Accra",
            "languages": "English",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/ghana-emoji.png",
        },
        {
            "id": "GRC",
            "code": "Euro",
            "name": "Greece",
            "phone": "30",
            "capital": "Athens",
            "languages": "GreekGreek",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/greece-emoji.png",
        },
        {
            "id": "GRD",
            "code": "East Caribbean Dollar",
            "name": "Grenada",
            "phone": "1 473",
            "capital": "St. George's",
            "languages": "English; Patois",
            "continent": "North America",
            "emoji": "https://img.icons8.com/emoji/48/null/grenada-emoji.png",
        },
        {
            "id": "GTM",
            "code": "Quetzal",
            "name": "Guatemala",
            "phone": "502",
            "capital": "Guatemala City",
            "languages": "Spanish",
            "continent": "North America",
            "emoji": "https://img.icons8.com/emoji/48/null/guatemala-emoji.png",
        },
        {
            "id": "GIN",
            "code": "Guinean Franc",
            "name": "Guinea",
            "phone": "224",
            "capital": "Conakry",
            "languages": "French",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/guinea-emoji.png",
        },
        {
            "id": "GNB",
            "code": "West African CFA Franc",
            "name": "Guinea-Bissau",
            "phone": "245",
            "capital": "Bissau",
            "languages": "Portuguese",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/guinea-bissau-emoji.png",
        },
        {
            "id": "GUY",
            "code": "Guyanese Dollar",
            "name": "Guyana",
            "phone": "592",
            "capital": "Georgetown",
            "languages": "English",
            "continent": "South America",
            "emoji": "https://img.icons8.com/emoji/48/null/guyana-emoji.png",
        },
        {
            "id": "HTI",
            "code": "Gourde",
            "name": "Haiti",
            "phone": "509",
            "capital": "Port-au-prince",
            "languages": "Haitian Creole; French",
            "continent": "North America",
            "emoji": "https://img.icons8.com/emoji/48/null/haiti-emoji.png",
        },
        {
            "id": "HND",
            "code": "Lempira",
            "name": "Honduras",
            "phone": "504",
            "capital": "Tegucigalpa",
            "languages": "Spanish",
            "continent": "North America",
            "emoji": "https://img.icons8.com/emoji/48/null/honduras-emoji.png",
        },
        {
            "id": "HUN",
            "code": "Forint",
            "name": "Hungary",
            "phone": "36",
            "capital": "Budapest",
            "languages": "Hungarian",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/hungary-emoji.png",
        },
        {
            "id": "IS",
            "code": "Icelandic Krona",
            "name": "Iceland",
            "phone": "354",
            "capital": "Reykjavík",
            "languages": "Icelandic",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/iceland-emoji.png",
        },
        {
            "id": "IND",
            "code": "Indian Rupee",
            "name": "India",
            "phone": "91",
            "capital": "New Delhi",
            "languages": "Hindi; English",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/india-emoji.png",
        },
        {
            "id": "IRQ",
            "code": "AFG",
            "name": "Indonesia",
            "phone": "964",
            "capital": "Jakarta",
            "languages": "Dani Persion, Pashto",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/indonesia-emoji.png",
        },
        {
            "id": "IRN",
            "code": "Rial",
            "name": "Iran",
            "phone": "98",
            "capital": "Kabul",
            "languages": "Persian",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/iran-emoji.png",
        },
        {
            "id": "IRQ",
            "code": "Iraqi Dinar",
            "name": "Iraq",
            "phone": "964",
            "capital": "Baghdad",
            "languages": "Arabic; Kurdish",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/iraq-emoji.png",
        },
        {
            "id": "IRL",
            "code": "Euro",
            "name": "Republic of Ireland",
            "phone": "353",
            "capital": "Dublin",
            "languages": "English; Irish",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/ireland-emoji.png",
        },
        {
            "id": "ISR",
            "code": "Shekel",
            "name": "Israel",
            "phone": "972",
            "capital": "Jerusalem",
            "languages": "Hebrew; Arabic",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/israel-emoji.png",
        },
        {
            "id": "ITA",
            "code": "Euro",
            "name": "Italy",
            "phone": "39",
            "capital": "Rome",
            "languages": "Italian",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/italy-emoji.png",
        },
        {
            "id": "JAM",
            "code": "Jamaican Dollar",
            "name": "Jamaica",
            "phone": "1 876",
            "capital": "Kingston",
            "languages": "English",
            "continent": "North America",
            "emoji": "https://img.icons8.com/emoji/48/null/jamaica-emoji.png",
        },
        {
            "id": "JPN",
            "code": "Yen",
            "name": "Japan",
            "phone": "81",
            "capital": "Tokyo",
            "languages": "Japanese",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/japan-emoji.png",
        },
        {
            "id": "JOR",
            "code": "Jordanian Dinar",
            "name": "Jordan",
            "phone": "962",
            "capital": "Amman",
            "languages": "Arabic",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/jordan-emoji.png",
        },
        {
            "id": "KAZ",
            "code": "Tenge",
            "name": "Kazakhstan",
            "phone": "7",
            "capital": "Astana",
            "languages": "Kazakh; Russian",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/kazakhstan-emoji.png",
        },
        {
            "id": "KEN",
            "code": "Kenyan Shilling",
            "name": "Kenya",
            "phone": "254",
            "capital": "Nairobi",
            "languages": "Swahili; English",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/kenya-emoji.png",
        },
        {
            "id": "KIR",
            "code": "Kiribati Dollar",
            "name": "Kiribati",
            "phone": "686",
            "capital": "Tarawa",
            "languages": "English; Gilbertese",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/kiribati-emoji.png",
        },
        {
            "id": "PRK",
            "code": "North Korean Won",
            "name": "North Korea",
            "phone": "850",
            "capital": "Pyongyang",
            "languages": "Korean",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/north-korea-emoji.png",
        },
        {
            "id": "KOR",
            "code": "South Korean Won",
            "name": "South Korea",
            "phone": "82",
            "capital": "Seoul",
            "languages": "Korean",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/south-korea-emoji.png",
        },
        {
            "id": "XK",
            "code": "Euro",
            "name": "Kosovo",
            "phone": "383",
            "capital": "Pristina",
            "languages": "Albanian; Serbian",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/kosovo-emoji.png",
        },
        {
            "id": "KWT",
            "code": "Kuwaiti Dollar",
            "name": "Kuwait",
            "phone": "965",
            "capital": "Kuwait City",
            "languages": "Arabic; English",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/kuwait-emoji.png",
        },
        {
            "id": "KGZ",
            "code": "Som",
            "name": "Kyrgyzstan",
            "phone": "996",
            "capital": "Bishkek",
            "languages": "Kyrgyz; Russian",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/kyrgyzstan-emoji.png",
        },
        {
            "id": "LAO",
            "code": "Kip",
            "name": "Laos",
            "phone": "856",
            "capital": "Vientiane",
            "languages": "Lao (Laotian)",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/laos-emoji.png",
        },
        {
            "id": "LVA",
            "code": "Lats",
            "name": "Latvia",
            "phone": "371",
            "capital": "Riga",
            "languages": "Latvian",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/latvia-emoji.png",
        },
        {
            "id": "LBN",
            "code": "Lebanese Pound",
            "name": "Lebanon",
            "phone": "961",
            "capital": "Beirut",
            "languages": "Arabic; French",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/lebanon-emoji.png",
        },
        {
            "id": "LSO",
            "code": "Loti",
            "name": "Lesotho",
            "phone": "266",
            "capital": "Maseru",
            "languages": "Sesotho; English",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/lesotho-emoji.png",
        },
        {
            "id": "LBR",
            "code": "Liberian Dollar",
            "name": "Liberia",
            "phone": "231",
            "capital": "Monrovia",
            "languages": "English",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/liberia-emoji.png",
        },
        {
            "id": "LBY",
            "code": "Libyan Dinar",
            "name": "Libya",
            "phone": "218",
            "capital": "Tripoli",
            "languages": "Arabic",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/libya-emoji.png",
        },
        {
            "id": "LTU",
            "code": "Lithuanian Litas",
            "name": "Liechtenstein",
            "phone": "370",
            "capital": "Vilnius",
            "languages": "Lithuanian",
            "continent": "asia",
            "emoji": "https://img.icons8.com/emoji/48/null/liechtenstein-emoji.png",
        },
        {
            "id": 1,
            "code": "AFG",
            "name": "Lithuania",
            "phone": "93",
            "capital": "Vilnius",
            "languages": "Dani Persion, Pashto",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/lithuania-emoji.png",
        },
        {
            "id": "LUX",
            "code": "Euro",
            "name": "Luxembourg",
            "phone": "352",
            "capital": "Luxembourg",
            "languages": "Luxembourgish",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/luxembourg-emoji.png",
        },
        {
            "id": "MKD",
            "code": "Macedonian Denar",
            "name": "Macedonia",
            "phone": "389",
            "capital": "Skopje",
            "languages": "Macedonian",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/north-macedonia-emoji.png",
        },{
            "id": "MDG",
            "code": "Malagasy Ariary",
            "name": "Madagascar",
            "phone": "261",
            "capital": "Antananarivo",
            "languages": "Malagasy; French; English",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/madagascar-emoji.png",
        },
        {
            "id": "MWI",
            "code": "Malawi Kwacha",
            "name": "Malawi",
            "phone": "265",
            "capital": "Lilongwe",
            "languages": "English",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/malawi-emoji.png",
        },
        {
            "id": "MYS",
            "code": "Ringgit",
            "name": "Malaysia",
            "phone": "60",
            "capital": "Kuala Lumpur",
            "languages": "Malay",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/malaysia-emoji.png",
        },
        {
            "id": "MDV",
            "code": "Maldivian Rufiyaa",
            "name": "Maldives",
            "phone": "960",
            "capital": "Malé",
            "languages": "Dhivehi",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/maldives-emoji.png",
        },
        {
            "id": "MLI",
            "code": "West African CFA Franc",
            "name": "Mali",
            "phone": "223",
            "capital": "Bamako",
            "languages": "French",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/mali-emoji.png",
        },
        {
            "id": "MHL",
            "code": "United States Dollar",
            "name": "Marshall Islands",
            "phone": "692",
            "capital": "Majuro",
            "languages": "Marshallese; English",
            "continent": "Oceania",
            "emoji": "https://img.icons8.com/emoji/48/null/marshall-islands-emoji.png",
        },
        {
            "id": "MRT",
            "code": "Ouguiya",
            "name": "Mauritania",
            "phone": "222",
            "capital": "Nouakchott",
            "languages": "Arabic",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/mauritania-emoji.png",
        },
        {
            "id": "MUS",
            "code": "Mauritian Rupee",
            "name": "Mauritius",
            "phone": "230",
            "capital": "Port Louis",
            "languages": "English",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/mauritius-emoji.png",
        },
        {
            "id": "MEX",
            "code": "Mexican Peso",
            "name": "Mexico",
            "phone": "52",
            "capital": "Mexico City",
            "languages": "Spanish",
            "continent": "North America",
            "emoji": "https://img.icons8.com/emoji/48/null/mexico-emoji.png",
        },
        {
            "id": "FSM",
            "code": "United States Dollar",
            "name": "Federal States of Micronesia",
            "phone": "691",
            "capital": "Palikir",
            "languages": "English",
            "continent": "Oceania",
            "emoji": "https://img.icons8.com/emoji/48/null/micronesia-emoji.png",
        },
        {
            "id": "MDA",
            "code": "Moldovan Leu",
            "name": "Moldova",
            "phone": "373",
            "capital": "Chisinau",
            "languages": "Moldovan (Romanian)",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/moldova-emoji.png",
        },
        {
            "id": "MCO",
            "code": "Euro",
            "name": "Monaco",
            "phone": "377",
            "capital": "Manaco",
            "languages": "French; Italian; English",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/monaco-emoji.png",
        },
        {
            "id": "MNE",
            "code": "Euro",
            "name": "Montenegro",
            "phone": "382",
            "capital": "Podgorica",
            "languages": "Montenegrin",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/montenegro-emoji.png",
        },
        {
            "id": "MAR",
            "code": "Moroccan Dirham",
            "name": "Morocco",
            "phone": "212",
            "capital": "Rabat",
            "languages": "Arabic",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/morocco-emoji.png",
        },
        {
            "id": "MOZ",
            "code": "Mozambican Metical",
            "name": "Mozambique",
            "phone": "258",
            "capital": "Maputo",
            "languages": "Portuguese",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/mozambique-emoji.png",
        },
        {
            "id": "MM",
            "code": "Kyat",
            "name": "Myanmar (Burma)",
            "phone": "95",
            "capital": "Naypyidaw",
            "languages": "Burmese",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/myanmar-burma-emoji.png",
        },
        {
            "id": "NAM",
            "code": "Namibian Dollar",
            "name": "Namibia",
            "phone": "264",
            "capital": "Windhoek",
            "languages": "English; Afrikaans; German",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/namibia-emoji.png",
        },
        {
            "id": "NPL",
            "code": "Nepalese Rupee",
            "name": "Nepal",
            "phone": "977",
            "capital": "Kathmandu",
            "languages": "Nepali",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/nepal-emoji.png",
        },
        {
            "id": "NLD",
            "code": "Euro",
            "name": "Netherlands",
            "phone": "31",
            "capital": "Amsterdam",
            "languages": "Dutch",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/netherlands-emoji.png",
        },
        {
            "id": "NZL",
            "code": "New Zealand Dollar",
            "name": "New Zealand",
            "phone": "64",
            "capital": "Wellington",
            "languages": "English",
            "continent": "Oceania",
            "emoji": "https://img.icons8.com/emoji/48/null/new-zealand-emoji.png",
        },
        {
            "id": "NIC",
            "code": "Cordoba",
            "name": "Nicaragua",
            "phone": "505",
            "capital": "Managua",
            "languages": "Spanish",
            "continent": "North America",
            "emoji": "https://img.icons8.com/emoji/48/null/nicaragua-emoji.png",
        },
        {
            "id": "NER",
            "code": "West African CFA Franc",
            "name": "Niger",
            "phone": "227",
            "capital": "Niamey",
            "languages": "French",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/niger-emoji.png",
        },
        {
            "id": "NGA",
            "code": "Naira",
            "name": "Nigeria",
            "phone": "234",
            "capital": "Abuja",
            "languages": "English",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/nigeria-emoji.png",
        },
        {
            "id": "NOR",
            "code": "Norwegian Krone",
            "name": "Norway",
            "phone": "47",
            "capital": "Oslo",
            "languages": "Norwegian",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/norway-emoji.png",
        },
        {
            "id": "OMN",
            "code": "Omani Rial",
            "name": "Oman",
            "phone": "968",
            "capital": "Muscat",
            "languages": "Arabic",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/oman-emoji.png",
        },
        {
            "id": "PAK",
            "code": "Pakistani Rupee",
            "name": "Pakistan",
            "phone": "92",
            "capital": "Islamabad",
            "languages": "Urdu; English",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/pakistan-emoji.png",
        },
        {
            "id": "PLW",
            "code": "United States Dollar",
            "name": "Palau",
            "phone": "680",
            "capital": "Ngerulmud",
            "languages": "English; Palauan",
            "continent": "Oceania",
            "emoji": "https://img.icons8.com/emoji/48/null/palau-emoji.png",
        },
        {
            "id": "PAN",
            "code": "Balboa",
            "name": "Panama",
            "phone": "507",
            "capital": "Panama City",
            "languages": "Spanish",
            "continent": "North America",
            "emoji": "https://img.icons8.com/emoji/48/null/panama-emoji.png",
        },
        {
            "id": "PNg",
            "code": "Papa New Guinean Kina",
            "name": "Papa New Guinea",
            "phone": "675",
            "capital": "Port Moresby",
            "languages": "English; Tok Pisin; Hiri Motu",
            "continent": "Oceania",
            "emoji": "https://img.icons8.com/emoji/48/null/papua-new-guinea-emoji.png",
        },
        {
            "id": "PRY",
            "code": "Guarani",
            "name": "Paraguay",
            "phone": "595",
            "capital": "Asunción",
            "languages": "Spanish; Guarani",
            "continent": "South America",
            "emoji": "https://img.icons8.com/emoji/48/null/paraguay-emoji.png",
        },
        {
            "id": "PER",
            "code": "Nuevo Sol",
            "name": "Peru",
            "phone": "51",
            "capital": "Lima",
            "languages": "Spanish",
            "continent": "South America",
            "emoji": "https://img.icons8.com/emoji/48/null/peru-emoji.png",
        },
        {
            "id": "PHL",
            "code": "Phillipine Peso",
            "name": "Phillipines",
            "phone": "63",
            "capital": "Manila",
            "languages": "Filipino; English",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/philippines-emoji.png",
        },
        {
            "id": "POL",
            "code": "Złoty",
            "name": "Poland",
            "phone": "48",
            "capital": "Warsaw",
            "languages": "Polish",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/poland-emoji.png",
        },
        {
            "id": "PRT",
            "code": "Euro",
            "name": "Portugal",
            "phone": "351",
            "capital": "Lisbon",
            "languages": "Portuguese",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/portugal-emoji.png",
        },
        {
            "id": "QAT",
            "code": "Qatari Riyal",
            "name": "Qatar",
            "phone": "974",
            "capital": "Doha",
            "languages": "Arabic",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/qatar-emoji.png",
        },
        {
            "id": "ROU",
            "code": "Romanian Rupee",
            "name": "Romania",
            "phone": "40",
            "capital": "Bucharest",
            "languages": "Romanian",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/romania-emoji.png",
        },
        {
            "id": "RUS",
            "code": "Ruble",
            "name": "Russia",
            "phone": "7",
            "capital": "Moscow",
            "languages": "Russian",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/russia-emoji.png",
        },
        {
            "id": "RWA",
            "code": "Rwandan Franc",
            "name": "Rwanda",
            "phone": "250",
            "capital": "Kigali",
            "languages": "Kinyarwanda; French; English",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/rwanda-emoji.png",
        },
        {
            "id": "KNA",
            "code": "East Caribbean Dollar",
            "name": "Saint Kitts and Nevis",
            "phone": "1 869",
            "capital": "Basseterre",
            "languages": "English",
            "continent": "North America",
            "emoji": "https://img.icons8.com/emoji/48/null/st-kitts--nevis-emoji.png",
        },
        {
            "id": "LCA",
            "code": "East Caribbean Dollar",
            "name": "Saint Lucia",
            "phone": "1 758",
            "capital": "Castries",
            "languages": "English; French",
            "continent": "North America",
            "emoji": "https://img.icons8.com/emoji/48/null/st-lucia-emoji.png",
        },
        {
            "id": "VCT",
            "code": "East Caribbean Dollar",
            "name": "Saint Vincent and The Grenadines",
            "phone": "1 784",
            "capital": "Kingstown",
            "languages": "English",
            "continent": "North America",
            "emoji": "https://img.icons8.com/emoji/48/null/st-vincent--grenadines-emoji.png",
        },
        {
            "id": "WSM",
            "code": "Tala",
            "name": "Samoa",
            "phone": "685",
            "capital": "Apia",
            "languages": "Samoan; English",
            "continent": "Oceania",
            "emoji": "https://img.icons8.com/emoji/48/null/samoa-emoji.png",
        },
        {
            "id": "SMR",
            "code": "Euro",
            "name": "San Marino",
            "phone": "378",
            "capital": "San Marino",
            "languages": "Italian",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/san-marino-emoji.png",
        },
        {
            "id": "STP",
            "code": "Dobra",
            "name": "Sao Tome and Principe",
            "phone": "239",
            "capital": "Sao Tome",
            "languages": "Portuguese",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/saint-thomas-and-prince-emoji.png",
        },
        {
            "id": "SAU",
            "code": "Saudi Riyal",
            "name": "Saudi Arabia",
            "phone": "966",
            "capital": "Riyadh",
            "languages": "Arabic",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/saudi-arabia-emoji.png",
        },
        {
            "id": "SEN",
            "code": "West African CFA Franc",
            "name": "Senegal",
            "phone": "221",
            "capital": "Dakar",
            "languages": "French",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/senegal-emoji.png",
        },
        {
            "id": "SRB",
            "code": "Serbian Dinar",
            "name": "Serbia",
            "phone": "381",
            "capital": "Belgrade",
            "languages": "Serbian",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/serbia-emoji.png",
        },
        {
            "id": "SYC",
            "code": "Seychoellois Rupee",
            "name": "Seychelles",
            "phone": "248",
            "capital": "Victoria",
            "languages": "Seychellois Creole;French; English",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/seychelles-emoji.png",
        },
        {
            "id": "SLE",
            "code": "Leone",
            "name": "Sierra Leone",
            "phone": "232",
            "capital": "Freetown",
            "languages": "Krio; English",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/sierra-leone-emoji.png",
        },
        {
            "id": "SGP",
            "code": "Singapore Dollar",
            "name": "Singapore",
            "phone": "65",
            "capital": "Singapore",
            "languages": "English; Malay;Mandarin Chinese",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/singapore-emoji.png",
        },
        {
            "id": "SVK",
            "code": "Euro",
            "name": "Slovakia",
            "phone": "421",
            "capital": "Bratislava",
            "languages": "Slovak",
            "continent": "North America",
            "emoji": "https://img.icons8.com/emoji/48/null/slovakia-emoji.png",
        },
        {
            "id": "SVN",
            "code": "Euro",
            "name": "Slovenia",
            "phone": "386",
            "capital": "Ljubljana",
            "languages": "Slovene",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/slovenia-emoji.png",
        },
        {
            "id": "SLB",
            "code": "Solomon Islands Dollar",
            "name": "Solomon Islands",
            "phone": "677",
            "capital": "Honiara",
            "languages": "DSolomons Pijin",
            "continent": "Oceania",
            "emoji": "https://img.icons8.com/emoji/48/null/solomon-islands-emoji.png",
        },
        {
            "id": "SOM",
            "code": "Somali Shilling",
            "name": "Somalia",
            "phone": "252",
            "capital": "Mogadishu",
            "languages": "Somali; Arabic",
            "continent": "asia",
            "emoji": "https://img.icons8.com/emoji/48/null/somalia-emoji.png",
        },
        {
            "id": "ZAF",
            "code": "Rand",
            "name": "South Africa",
            "phone": "27",
            "capital": "Cape Town",
            "languages": "Zulu; Xhosa; Afrikaans",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/south-africa-emoji.png",
        },
        {
            "id": "ESP",
            "code": "Euro",
            "name": "Spain",
            "phone": "34",
            "capital": "Madrid",
            "languages": "Spanish",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/ceuta--melilla-emoji.png",
        },
        {
            "id": "LKA",
            "code": "Sri Lankan Rupee",
            "name": "Sri Lanka",
            "phone": "94",
            "capital": "Sri Jayawardenapura-kotte",
            "languages": "Sinhala; Tamil",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/sri-lanka-emoji.png",
        },
        {
            "id": "SDN",
            "code": "Sudanese Pound",
            "name": "Sudan",
            "phone": "249",
            "capital": "Khartoum",
            "languages": "Arabic; English",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/sudan-emoji.png",
        },
        {
            "id": "SUR",
            "code": "Surinamese Dollar",
            "name": "Suriname",
            "phone": "597",
            "capital": "Paramaribo",
            "languages": "Dutch",
            "continent": "South America",
            "emoji": "https://img.icons8.com/emoji/48/null/suriname-emoji.png",
        },
        {
            "id": "SWZ",
            "code": "Lilangeni",
            "name": "Swaziland",
            "phone": "268",
            "capital": "Mata-utu",
            "languages": "English; SiSwati",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/color/48/null/swaziland.png",
        },
        {
            "id": "SWe",
            "code": "Swedish Krona",
            "name": "Sweden",
            "phone": "46",
            "capital": "Stockholm",
            "languages": "Swedish",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/switzerland-emoji.png",
        },
        {
            "id": "CHE",
            "code": "Swiss Franc",
            "name": "Switzerland",
            "phone": "41",
            "capital": "Bern",
            "languages": "German; French; Italian",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/switzerland-emoji.png",
        },
        {
            "id": "SYR",
            "code": "Syrian Pound",
            "name": "Syria",
            "phone": "963",
            "capital": "Damascus",
            "languages": "Arabic",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/syria-emoji.png",
        },
        {
            "id": 1,
            "code": "Legislative Yuan",
            "name": "Taiwan",
            "phone": "886",
            "capital": "Taipei",
            "languages": "Standart Chinese",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/taiwan-emoji.png",
        },
        {
            "id": "TJK",
            "code": "Somoni",
            "name": "Tajikistan",
            "phone": "992",
            "capital": "Dushanbe",
            "languages": "Tajik; Russian",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/tajikistan-emoji.png",
        },
        {
            "id": "TZA",
            "code": "Tanzanian Schilling",
            "name": "Tanzania",
            "phone": "255",
            "capital": "Dodoma",
            "languages": "Swahili",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/tanzania-emoji.png",
        },
        {
            "id": "THA",
            "code": "Thai Baht",
            "name": "Thailand",
            "phone": "66",
            "capital": "Bangkok",
            "languages": "Thai",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/thailand-emoji.png",
        },
        {
            "id": "TGO",
            "code": "West African CFA Franc",
            "name": "Togo",
            "phone": "228",
            "capital": "Lomé",
            "languages": "French",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/togo-emoji.png",
        },
        {
            "id": "TON",
            "code": "Pa'anga",
            "name": "Tonga",
            "phone": "676",
            "capital": "Nuku alofa",
            "languages": "Tongan; English",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/tonga-emoji.png",
        },
        {
            "id": "TTO",
            "code": "Trinidad and Tobago Dollar",
            "name": "Trinidad and Tobago ",
            "phone": "1 868",
            "capital": "Port Of Spain",
            "languages": "English",
            "continent": "North America",
            "emoji": "https://img.icons8.com/emoji/48/null/trinidad--tobago-emoji.png",
        },
        {
            "id": "TUN",
            "code": "Tunisian Dinar",
            "name": "Tunisia",
            "phone": "216",
            "capital": "Tunis",
            "languages": "Tunisian; French",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/tunisia-circular-emoji.png",
        },
        {
            "id": "TUR",
            "code": "Turkish Lira",
            "name": "Turkey",
            "phone": "90",
            "capital": "Ankara",
            "languages": "Turkish",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/turkey-flag-emoji.png",
        },
        {
            "id": "TKM",
            "code": "Turkmen New Manat",
            "name": "Turkmenistan",
            "phone": "993",
            "capital": "Ashgabat",
            "languages": "Turkmen; Russian",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/turkmenistan-emoji.png",
        },
        {
            "id": "TUV",
            "code": "Tuvaluan Dollar",
            "name": "Tuvalu",
            "phone": "688",
            "capital": "Funafuti",
            "languages": "Tuvaluan; English",
            "continent": "Oceania",
            "emoji": "https://img.icons8.com/emoji/48/null/tuvalu-emoji.png",
        },
        {
            "id": "UGA",
            "code": "Ugandan Shilling",
            "name": "Uganda",
            "phone": "256",
            "capital": "Kampala",
            "languages": "Swahili; English",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/uganda-emoji.png",
        },
        {
            "id": "UKR",
            "code": "Hryvnia",
            "name": "Ukraine",
            "phone": "380",
            "capital": "Kiev",
            "languages": "Ukranian; Russian",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/ukraine-emoji.png",
        },
        {
            "id": "ARE",
            "code": "Dirham",
            "name": "United Arab Emirates",
            "phone": "971",
            "capital": "Abu Dhabi",
            "languages": "Arabic",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/united-arab-emirates-emoji.png",
        },
        {
            "id": "GBR",
            "code": "Pound Sterling",
            "name": "United Kingdom",
            "phone": "44",
            "capital": "London",
            "languages": "English",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/united-kingdom-emoji.png",
        },
        {
            "id": "USA",
            "code": "United States Dollar",
            "name": "United States of America",
            "phone": "1",
            "capital": "Washington D.C.",
            "languages": "English; Spanish",
            "continent": "North America",
            "emoji": "https://img.icons8.com/emoji/48/null/united-states-emoji.png",
        },
        {
            "id": "URY",
            "code": "Uruguayan Peso",
            "name": "Uruguay",
            "phone": "598",
            "capital": "Montevideo",
            "languages": "Spanish",
            "continent": "South America",
            "emoji": "https://img.icons8.com/emoji/48/null/uruguay-emoji.png",
        },
        {
            "id": "Uzb",
            "code": "UZS",
            "name": "Uzbekistan",
            "phone": "998",
            "capital": "Tashkent",
            "languages": "Uzbek; Russian",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/uzbekistan-emoji.png",
        },
        {
            "id": "VUT",
            "code": "Vanuatu Vatu",
            "name": "Vanuatu",
            "phone": "678",
            "capital": "Port Vila",
            "languages": "Bislama; English; French",
            "continent": "Oceania",
            "emoji": "https://img.icons8.com/emoji/48/null/vanuatu-emoji.png",
        },
        {
            "id": 1,
            "code": "Euro",
            "name": "Vatican City",
            "phone": "39",
            "capital": "Vatican City",
            "languages": "Latin, Italian",
            "continent": "Europe",
            "emoji": "https://img.icons8.com/emoji/48/null/vatican-city-emoji.png",
        },{
            "id": "VEN",
            "code": "Bolivar Fuerte",
            "name": "Venezuela",
            "phone": "58",
            "capital": "Caracas",
            "languages": "Spanish",
            "continent": "South America",
            "emoji": "https://img.icons8.com/emoji/48/null/venezuela-emoji.png",
        },
        {
            "id": "VNM",
            "code": "Dong",
            "name": "Vietnam",
            "phone": "84",
            "capital": "Hanoi",
            "languages": "Vietnamese",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/vietnam-emoji.png",
        },
        {
            "id": "YEM",
            "code": "Yemeni Rial",
            "name": "Yemen",
            "phone": "967",
            "capital": "Sana'a",
            "languages": "Arabic",
            "continent": "Asia",
            "emoji": "https://img.icons8.com/emoji/48/null/yemen-emoji.png",
        },
        {
            "id": "ZMB",
            "code": "Zambian Kwacha",
            "name": "Zambia",
            "phone": "260",
            "capital": "Lusaka",
            "languages": "English",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/zambia-emoji.png",
        },
        {
            "id": "ZWE",
            "code": "United States Dollar",
            "name": "Zimbabwe",
            "phone": "263",
            "capital": "Harare",
            "languages": "English",
            "continent": "Africa",
            "emoji": "https://img.icons8.com/emoji/48/null/zimbabwe-emoji.png",
        },
    ]
}
export default data